@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jan 29 14:12:48 +0530 2024
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim seven_seg_display_behav -key {Behavioral:sim_1:Functional:seven_seg_display} -tclbatch seven_seg_display.tcl -view C:/Users/mauli/OneDrive/Desktop/DD Lab/Projects/Lab_02/lab_02_full_adder/seven_seg_display_behav.wcfg -log simulate.log"
call xsim  seven_seg_display_behav -key {Behavioral:sim_1:Functional:seven_seg_display} -tclbatch seven_seg_display.tcl -view C:/Users/mauli/OneDrive/Desktop/DD Lab/Projects/Lab_02/lab_02_full_adder/seven_seg_display_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
